extends Node
## Things in the world that move on their own.
##
## This is the entity primitive, and the dog and the cat are its first two
## users. Nothing in this file knows what a dog is. A critter is a named state
## machine over the tile grid: each state has a **goal** (hold, approach,
## retreat, wander) and a distance to keep, and **transitions** move between
## states on a player action, on distance, on time, or on the critter failing to
## make progress. All of it is in data/content/critters.json, so the third
## animal — and the mountain woman's escorted friend in #78 — is a data file.
##
## Four decisions, all of which are the interesting part:
##
##   * **Lag, not mirroring.** An approach state may name a `trail`: it aims at
##     the cell the target stood on N moves ago rather than the one it is on.
##     A follower that occupies your previous cell exactly is uncanny and reads
##     as a rendering bug; two cells of history is the cheapest cure.
##   * **Hysteresis, not a threshold.** A wary animal needs *different* numbers
##     for coming closer and for backing off. One threshold, used in both
##     directions, produces an animal that vibrates on the boundary. The cat
##     breaks at 2, runs to 6, returns to 4 and only sets off again at 5.
##   * **Giving up is a behaviour.** A follower wedged behind furniture that
##     never recovers is the classic failure. `stray` counts move attempts that
##     got no closer; a state's `recover` says how many of those it takes before
##     the critter abandons the path and reappears at the edge of its band. The
##     same counter is readable as a transition condition, so "cornered, it
##     stops trying" is data rather than a special case.
##   * **Nothing simulates off screen.** `_process` returns immediately unless
##     the overworld is the current screen, because a cat walking around a house
##     nobody is looking at is simulation spent on nothing. Being *where it
##     should be* on return is a different problem and is solved on re-entry:
##     see resolve_on_return().
##
## Steps are the player's currency and the player's alone. A critter's movement
## is on a wall-clock pace expressed as a multiple of `critter.tick_seconds`,
## so it costs nothing and does not stop when the step budget does.
##
## The renderer reads views() and draws what it says. It is not told about
## states, distances or paths — see the header on views().

signal changed   ## a critter changed state, spawned, or was cleared

const SAVE_PATH := "user://heroes_critters.json"
const SPECIES_PATH := "res://data/content/critters.json"
const VERSION := 1

## Column order of the walk cycle, and the row order of the facings. Identical
## to HJTileWorld's CYCLE and FACINGS, and identical for the same reason: the
## animal sheets are generated by the same tools/make_sprites.py that generates
## the player, in the same layout, so one loader serves both.
const CYCLE := [1, 0, 2, 0]
const FIDGET_COL := 3
const FACING_ROW := {
	Vector2i.DOWN: 0, Vector2i.UP: 1, Vector2i.LEFT: 2, Vector2i.RIGHT: 3,
}
const CARDINALS := [Vector2i.DOWN, Vector2i.UP, Vector2i.LEFT, Vector2i.RIGHT]

## The events a placement can fire at a critter. Read by tools/validate_data.py
## as the vocabulary `critter_events`, so data naming one that does not exist is
## an error rather than an animal that ignores you.
const EVENTS := ["petted"]

## How much of the player's recent path is remembered, so `trail` has something
## to aim at. Eight is four times the deepest trail any state uses.
const TRAIL_LENGTH := 8

## How long a critter is only visible-adjacent enough for its `say` line to be
## worth printing. Beyond this the player cannot see what happened.
const EARSHOT := 14

## At most this many think-ticks are made up in one frame. A frame that hitched
## for two seconds must not teleport the cat across the house.
const MAX_CATCHUP := 6

## Position changes constantly, so it is not written on every one of them.
const SAVE_SECONDS := 3.0

## Overridable, so the simulation harness and the self-test do not write
## critters into the player's own file. Same reasoning as HJBuffs.path.
var path := SAVE_PATH

## [{ key, id, state, cell, from, facing, home, held, stray, cool, t, span,
##    fidget, rng }] — one per placed animal. `key` is the placement's identity,
## so two cats in one house are two critters of one species.
var _live: Array = []
var _species: Dictionary = {}          ## id -> definition
var _species_loaded := false
var _placements: Array = []            ## [{ key, critter, x, y }], or [] = read the world
var _placements_loaded := false
var _spawned := false
var _world: HJWorld = null
var _trail: Array[Vector2i] = []       ## the player's recent cells, oldest first
var _player := Vector2i(-1, -1)
var _accum := 0.0
var _save_in := 0.0
var _dirty := false
var _run_seed := 0
## The run the live set belongs to. A new loop is new animals: the dog that
## followed you yesterday is asleep by the stove again, the same rule Buffs and
## Steps follow. Nothing calls clear_all() on a run boundary because Game.gd is
## not this system's to edit, so the boundary is *detected* instead — which is
## more robust anyway, since it also catches a run replaced by a load.
var _seed_seen := 0


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_PAUSABLE
	if Events != null:
		Events.screen_changed.connect(_on_screen_changed)


# --- the clock -----------------------------------------------------------------

## Nothing here runs unless the overworld is on screen. See the header.
func _process(delta: float) -> void:
	if not _on_overworld():
		return
	_check_run()
	_ensure()
	if _live.is_empty():
		return
	var run: HJRun = Game.run
	if run != null and run.world_pos.x >= 0:
		note_player(run.world_pos)
	var tick := tick_seconds()
	_accum += delta
	var made := 0
	while _accum >= tick and made < MAX_CATCHUP:
		_accum -= tick
		made += 1
		think(tick)
	if made >= MAX_CATCHUP:
		_accum = 0.0
	animate(delta)
	_flush(delta)


func _on_screen_changed(screen_name: String) -> void:
	if screen_name == "overworld":
		_ensure()
		var run: HJRun = Game.run
		if run != null and run.world_pos.x >= 0:
			resolve_on_return(run.world_pos)
	elif _dirty:
		save_state()


## A different run than the one the live animals were spawned for wipes them.
func _check_run() -> void:
	var now := _run_seed_now()
	if now == _seed_seen:
		return
	_seed_seen = now
	_run_seed = now
	_spawned = false
	_live.clear()
	_trail.clear()
	_player = Vector2i(-1, -1)


## For the harness: pretend to be a given run, so a save written by one test
## cannot be read by the next.
func use_run_seed(value: int) -> void:
	_run_seed = value
	_seed_seen = value


func _on_overworld() -> bool:
	return Game != null and Game.screen == "overworld" and Game.has_active_run()


# --- tunables ------------------------------------------------------------------
# Literal keys, so tools/validate_data.py can see that something reads them.

func tick_seconds() -> float:
	return maxf(0.02, Rules.value("critter.tick_seconds", {}, 0.17))


func fidget_seconds() -> float:
	return maxf(0.5, Rules.value("critter.fidget_seconds", {}, 3.4))


func path_budget() -> int:
	return maxi(16, int(Rules.value("critter.path_budget", {}, 240.0)))


# --- the catalogue -------------------------------------------------------------

## The species definitions. Read straight from the file rather than through
## Content, which does not merge a `critters` key — four lines in
## Content.load_all would fix that and is the obvious follow-up. The same
## reasoning HJInteractables gives for reading the world file itself applies:
## better a one-off parse than reaching into a loader this system does not own.
func species(id: String) -> Dictionary:
	_load_species()
	return _species.get(id, {})


func all_species() -> Array:
	_load_species()
	return _species.values()


func _load_species() -> void:
	if _species_loaded:
		return
	_species_loaded = true
	var parsed: Variant = Content.read_json(SPECIES_PATH)
	if not (parsed is Dictionary):
		return
	for entry in (parsed as Dictionary).get("critters", []):
		if entry is Dictionary and (entry as Dictionary).has("id"):
			_species[String((entry as Dictionary)["id"])] = entry


## Replace the catalogue. For the simulation harness, which builds an escort
## species that is not shipped in order to prove one can be.
func use_species(list: Array) -> void:
	_species.clear()
	for entry in list:
		if entry is Dictionary and (entry as Dictionary).has("id"):
			_species[String((entry as Dictionary)["id"])] = entry
	_species_loaded = true
	_spawned = false
	_live.clear()


func use_path(new_path: String) -> void:
	path = new_path


func use_world(w: HJWorld) -> void:
	_world = w


## Replace where the animals stand: [{ key, critter, x, y }]. For the harness
## and for tools, the same contract HJInteractables.use_placements keeps.
func use_placements(list: Array) -> void:
	_placements = list
	_placements_loaded = true
	_spawned = false
	_live.clear()


# --- spawning ------------------------------------------------------------------

func world() -> HJWorld:
	if _world == null:
		_world = HJWorld.shared()
	return _world


## Where the animals are, from the world's own interactable placements. A
## catalogue entry carrying a `critter` key is the seam: the house agent drags a
## dog around in Tiled and this picks it up, and retyping it to a cat is a data
## edit. Nothing about the placement mentions behaviour.
func placements() -> Array:
	if _placements_loaded:
		return _placements
	_placements_loaded = true
	_placements = []
	for entry in world().interactables:
		if not (entry is Dictionary):
			continue
		var placement: Dictionary = entry
		var def := Content.interactable(String(placement.get("type", "")))
		var critter_id := String(def.get("critter", ""))
		if critter_id == "":
			continue
		_placements.append({
			"key": HJInteractables.key_of(placement),
			"critter": critter_id,
			"x": int(placement.get("x", 0)),
			"y": int(placement.get("y", 0)),
		})
	return _placements


func _ensure() -> void:
	if _spawned:
		return
	_spawned = true
	if not load_state():
		spawn_all()


## Put every placed animal back at its home cell in its starting state.
func spawn_all() -> void:
	_live.clear()
	_trail.clear()
	_run_seed = _run_seed_now()
	_seed_seen = _run_seed
	for entry in placements():
		var placement: Dictionary = entry
		var def := species(String(placement.get("critter", "")))
		if def.is_empty():
			push_warning("Critters: placement %s names no critter '%s'"
				% [String(placement.get("key", "?")), String(placement.get("critter", ""))])
			continue
		var home := Vector2i(int(placement.get("x", 0)), int(placement.get("y", 0)))
		_live.append(_make(String(placement.get("key", "")),
			String(placement.get("critter", "")), def, home, home,
			String(def.get("start", ""))))
	_spawned = true
	_dirty = true
	changed.emit()


func _make(key: String, id: String, def: Dictionary, home: Vector2i,
		cell: Vector2i, state: String) -> Dictionary:
	# Seeded from the key so two animals never fidget or mooch in lockstep, and
	# so a reload gives the same one the same rhythm.
	var rng := RandomNumberGenerator.new()
	rng.seed = hash(key) ^ (_run_seed * 2654435761)
	return {
		"key": key, "id": id, "state": state,
		"cell": cell, "from": cell, "facing": Vector2i.DOWN, "home": home,
		"held": 0.0, "stray": 0, "cool": 0.0, "t": 1.0, "span": 0.2,
		"fidget": rng.randf() * fidget_seconds(), "rng": rng,
	}


## Nothing carries between runs. A dog that followed you yesterday is asleep by
## the stove again, the same rule Buffs and Steps follow.
func clear_all() -> void:
	_live.clear()
	_trail.clear()
	_spawned = false
	_dirty = false
	if FileAccess.file_exists(path):
		DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
	changed.emit()


# --- the read API for the renderer ---------------------------------------------
#
# Everything the Y-sorted scenery pass needs and nothing it does not. One entry
# per animal, per frame:
#
#   sprite  the sheet id; sheet_path() turns it into a res:// path. The sheet is
#           4 columns x 4 rows of 32x32 cells, generated by
#           tools/make_sprites.py in the same layout as player.png.
#   row     which row of the sheet: 0 down, 1 up, 2 left, 3 right.
#   col     which column: the walk cycle while moving, 0 or the fidget column
#           while still. Already resolved — the caller does not need CYCLE.
#   cell    the tile it occupies, and the row to Y-sort it on.
#   from,t  the tile it is crossing from and how far across, 0..1. Draw at
#           Vector2(from).lerp(Vector2(cell), t) * TILE, anchored bottom-centre
#           of the cell exactly like a prop, so it occludes and is occluded by
#           the same rule.
#
# Nothing in here is a Godot type the renderer has to interpret, and nothing
# about state, distance or pathing leaks through.
func views() -> Array:
	_ensure()
	var out: Array = []
	for entry in _live:
		var c: Dictionary = entry
		var def := species(String(c["id"]))
		var moving: bool = float(c["t"]) < 1.0
		var col := 0
		if moving:
			col = int(CYCLE[int(round(float(c["t"]) * 3.0)) % CYCLE.size()])
		elif float(c["fidget"]) < 0.28:
			col = FIDGET_COL
		out.append({
			"key": String(c["key"]),
			"id": String(c["id"]),
			"sprite": String(def.get("sprite", String(c["id"]))),
			"state": String(c["state"]),
			"cell": c["cell"], "from": c["from"], "t": float(c["t"]),
			"row": int(FACING_ROW.get(c["facing"], 0)),
			"col": col,
			"moving": moving,
		})
	return out


static func sheet_path(sprite: String) -> String:
	return "res://assets/sprites/%s.png" % sprite


## The cells the animals were placed on. The prop plane still carries a static
## dog and a static cat there — they were props before they could walk — so the
## renderer must skip the prop on these cells or the dog leaves a copy of
## himself behind. Cheap to ask once per draw; there are two of them.
func home_cells() -> Dictionary:
	_ensure()
	var out: Dictionary = {}
	for entry in _live:
		out[(entry as Dictionary)["home"]] = true
	return out


## Where a placed animal is standing now, or the placement's own cell if it is
## not alive. HJInteractables asks this so the Pet prompt follows the dog rather
## than staying on the rug he got up from.
func cell_of(key: String) -> Vector2i:
	var c := _find(key)
	return c["cell"] if not c.is_empty() else Vector2i(-1, -1)


func state_of(key: String) -> String:
	var c := _find(key)
	return String(c["state"]) if not c.is_empty() else ""


func alive(key: String) -> bool:
	return not _find(key).is_empty()


func count() -> int:
	_ensure()
	return _live.size()


# --- being acted on ------------------------------------------------------------

## Fire an event at one animal. Returns true if it moved state, which is what
## makes petting the dog and petting the cat do opposite things with no branch
## anywhere: the asymmetry is two rows of data.
func event(key: String, name: String) -> bool:
	if not EVENTS.has(name):
		push_warning("Critters: no such event '%s'" % name)
		return false
	_ensure()
	var c := _find(key)
	if c.is_empty():
		return false
	return _transition(c, name)


## Where the player is. Fed from HJRun.world_pos each frame, and by the harness
## directly. The history is what `trail` aims at.
func note_player(cell: Vector2i) -> void:
	if cell == _player:
		return
	_player = cell
	_trail.append(cell)
	while _trail.size() > TRAIL_LENGTH:
		_trail.remove_at(0)


## Coming back to the overworld from somewhere the world was not being drawn.
##
## The alternative — simulating while the player is inside an anomaly — spends
## work on something nobody can see and produces a dog that walked a route
## nobody watched. But the dog still has to be *where he should be*, so the
## question is resolved on re-entry instead: anything whose state is trying to
## close on the player is placed at the edge of its band, and anything that was
## keeping its distance is left exactly where it stood.
func resolve_on_return(cell: Vector2i) -> void:
	_ensure()
	_trail.clear()
	note_player(cell)
	for entry in _live:
		var c: Dictionary = entry
		var st := _state_def(c)
		if String(st.get("goal", "hold")) != "approach":
			continue
		if _target_kind(st) != "player":
			continue
		var keep := int(st.get("keep", 1))
		if _chebyshev(c["cell"], cell) <= maxi(1, keep + 1):
			continue
		_place_near(c, cell, keep)
	_dirty = true
	changed.emit()


# --- the tick ------------------------------------------------------------------

## One think-tick: every critter tests its transitions and then, if its pace has
## come round, takes at most one step. Public so the harness can drive it
## without a frame loop; `seconds` is how much clock the tick represents.
func think(seconds: float) -> void:
	_ensure()
	for entry in _live:
		var c: Dictionary = entry
		c["held"] = float(c["held"]) + seconds
		c["cool"] = maxf(0.0, float(c["cool"]) - seconds)
		_transition(c, "")
		if float(c["cool"]) > 0.0:
			continue
		var st := _state_def(c)
		var pace := maxf(0.05, float(st.get("pace", 1.0))) * tick_seconds()
		c["cool"] = pace
		_move(c, st, pace)


## Advance the tweens and the idle fidget. Split from think() because animation
## is per frame and behaviour is per tick, and mixing them makes the behaviour
## frame-rate dependent — which is exactly the bug a distance series cannot see.
func animate(delta: float) -> void:
	var fidget := fidget_seconds()
	for entry in _live:
		var c: Dictionary = entry
		if float(c["t"]) < 1.0:
			c["t"] = minf(1.0, float(c["t"]) + delta / maxf(0.01, float(c["span"])))
			if float(c["t"]) >= 1.0:
				c["from"] = c["cell"]
		else:
			# A perfectly still animal is furniture. Every critter twitches on
			# its own phase, so two of them in one room are never in step.
			c["fidget"] = fmod(float(c["fidget"]) + delta, fidget)


# --- transitions ---------------------------------------------------------------

func _state_def(c: Dictionary) -> Dictionary:
	var def := species(String(c["id"]))
	return (def.get("states", {}) as Dictionary).get(String(c["state"]), {})


## First matching rule wins, so order in the data is priority. One transition
## per tick at most: a chain that fires three rules in one tick is a state
## machine whose intermediate states nobody can see.
func _transition(c: Dictionary, fired: String) -> bool:
	var def := species(String(c["id"]))
	for entry in def.get("transitions", []):
		if not (entry is Dictionary):
			continue
		var rule: Dictionary = entry
		if not _from_matches(rule.get("from", "*"), String(c["state"])):
			continue
		var on := String(rule.get("on", ""))
		if on != fired:
			continue          # "" is the ordinary tick; a named event is not
		if not _conditions_met(c, rule.get("when", {})):
			continue
		_enter(c, String(rule.get("to", "")))
		var effect: Variant = rule.get("effect", null)
		if effect is Dictionary and Game != null and Game.has_active_run():
			# The same effect vocabulary hooks, interactables and objectives
			# use, so an escort that fails can set a run tag without this file
			# knowing what a quest is.
			Game.apply_effects([effect])
		return true
	return false


static func _from_matches(from: Variant, state: String) -> bool:
	if from is Array:
		return (from as Array).has(state)
	var name := String(from)
	return name == "*" or name == state


func _enter(c: Dictionary, state: String) -> void:
	c["state"] = state
	c["held"] = 0.0
	c["stray"] = 0
	c["cool"] = 0.0
	var st := _state_def(c)
	var line := String(st.get("say", ""))
	if line != "" and Events != null and _player.x >= 0 \
			and _chebyshev(c["cell"], _player) <= EARSHOT:
		Events.logged.emit(line, "info")
	_dirty = true
	changed.emit()


## The conditions a transition may test. Read by tools/validate_data.py as the
## vocabulary `critter_conditions`, so a typo in the data is an error rather
## than a rule that quietly never fires.
##
##   dist_gte / dist_lte  chebyshev distance to the state's target, in cells
##   held_gte             seconds spent in the current state
##   stray_gte            consecutive move attempts that made no progress
##   has_tag / lacks_tag  a run tag, so quest state can gate an animal
func _conditions_met(c: Dictionary, when: Variant) -> bool:
	if not (when is Dictionary):
		return true
	var dist := _chebyshev(c["cell"], _target_cell(c, _state_def(c), 0))
	for key in (when as Dictionary).keys():
		var want: Variant = (when as Dictionary)[key]
		match String(key):
			"dist_gte":
				if dist < int(want):
					return false
			"dist_lte":
				if dist > int(want):
					return false
			"held_gte":
				if float(c["held"]) < float(want):
					return false
			"stray_gte":
				if int(c["stray"]) < int(want):
					return false
			"has_tag":
				if Game == null or not Game.has_tag(String(want)):
					return false
			"lacks_tag":
				if Game != null and Game.has_tag(String(want)):
					return false
			_:
				push_warning("Critters: condition '%s' is not implemented" % String(key))
				return false
	return true


# --- moving --------------------------------------------------------------------

static func _target_kind(st: Dictionary) -> String:
	return String(st.get("target", "player"))


## The cell this state is measured against. `trail` is the lag: aim at where the
## target was N moves ago rather than where it is, so the animal follows a path
## instead of mirroring a position.
func _target_cell(c: Dictionary, st: Dictionary, trail: int) -> Vector2i:
	if _target_kind(st) == "home":
		return c["home"]
	if _player.x < 0:
		return c["cell"]
	if trail <= 0 or _trail.size() <= 1:
		return _player
	return _trail[maxi(0, _trail.size() - 1 - trail)]


func _move(c: Dictionary, st: Dictionary, span: float) -> void:
	var goal := String(st.get("goal", "hold"))
	var keep := int(st.get("keep", 1))
	var aim := _target_cell(c, st, int(st.get("trail", 0)))
	var before := _chebyshev(c["cell"], aim)
	var step := _step_for(goal, c, st, aim, keep)

	if step == Vector2i.ZERO:
		# Facing still matters when standing: a cat that watches you is doing
		# something, and a cat frozen facing a wall is a bug that looks like art.
		if goal == "hold" or goal == "wander":
			_face_toward(c, _target_cell(c, st, 0))
		if goal == "approach" and before > keep:
			_lose_ground(c, st)
		elif goal == "retreat" and before < keep:
			_lose_ground(c, st)
		else:
			c["stray"] = 0
		return

	c["from"] = c["cell"]
	c["cell"] = c["cell"] + step
	c["facing"] = step
	c["t"] = 0.0
	c["span"] = span
	var after := _chebyshev(c["cell"], aim)
	if (goal == "approach" and after < before) or (goal == "retreat" and after > before) \
			or goal == "wander":
		c["stray"] = 0
	else:
		_lose_ground(c, st)
	_dirty = true


## No progress this attempt. Past a state's `recover` the critter stops trying
## to walk there and reappears at the edge of its band, which is the difference
## between a dog that got stuck behind a chair for a moment and one that is lost
## for the rest of the run.
func _lose_ground(c: Dictionary, st: Dictionary) -> void:
	c["stray"] = int(c["stray"]) + 1
	var recover := int(st.get("recover", 0))
	if recover <= 0 or int(c["stray"]) < recover:
		return
	if String(st.get("goal", "hold")) != "approach":
		return
	_place_near(c, _target_cell(c, st, 0), int(st.get("keep", 1)))
	c["stray"] = 0


## One step, or Vector2i.ZERO for staying put. The `match` here is the goal
## vocabulary, and tools/validate_data.py reads it as `critter_goals` so the
## schema cannot claim a goal the engine does not implement.
func _step_for(goal: String, c: Dictionary, st: Dictionary, aim: Vector2i,
		keep: int) -> Vector2i:
	match goal:
		"hold":
			return Vector2i.ZERO
		"approach":
			if _chebyshev(c["cell"], aim) <= keep:
				return Vector2i.ZERO
			return _toward(c, aim)
		"retreat":
			if _chebyshev(c["cell"], aim) >= keep:
				return Vector2i.ZERO
			return _away(c, aim)
		"wander":
			return _mooch(c, st, keep)
	push_warning("Critters: goal '%s' is not implemented" % goal)
	return Vector2i.ZERO


## A step along the shortest walkable path, or the best greedy guess if the
## target is further away than the search is allowed to look.
##
## The flood runs outward from the *target*, not from the animal, which is what
## makes it a gradient rather than a route: the step is simply the neighbour
## with the lowest number on it, and the answer survives the target moving one
## cell without any of it being recomputed as a path.
func _toward(c: Dictionary, aim: Vector2i) -> Vector2i:
	var here: Vector2i = c["cell"]
	var field := _flood(aim, here)
	var best := Vector2i.ZERO
	if field.has(here):
		var best_d: int = int(field[here])
		for d in CARDINALS:
			var n: Vector2i = here + d
			if not field.has(n) or _occupied(n, c):
				continue
			if int(field[n]) < best_d:
				best_d = int(field[n])
				best = d
		if best != Vector2i.ZERO:
			return best
	# Out of reach of the flood, or every downhill neighbour is standing room
	# for something else. Fall back to a greedy axis step, which is right far
	# more often than it is wrong and cannot loop, because `stray` is counting.
	return _greedy(here, aim, c)


func _away(c: Dictionary, aim: Vector2i) -> Vector2i:
	var here: Vector2i = c["cell"]
	var now := _chebyshev(here, aim)
	var gain := Vector2i.ZERO
	var level := Vector2i.ZERO
	for d in CARDINALS:
		var n: Vector2i = here + d
		if not _walkable(n) or _occupied(n, c):
			continue
		var far := _chebyshev(n, aim)
		if far > now:
			# Prefer carrying on the way it was already going, so a cat with two
			# equally good escapes does not dither between them.
			if gain == Vector2i.ZERO or d == c["facing"]:
				gain = d
		elif far == now and (level == Vector2i.ZERO or d == c["facing"]):
			level = d
	# Sidestepping when there is no ground to gain is what a cornered animal
	# does. It counts as no progress, so `stray_gte` can end the panic.
	return gain if gain != Vector2i.ZERO else level


## Mooching: mostly standing about, occasionally a cell, never further than
## `keep` from home. Nothing uses this to escape anything — it is the difference
## between an animal at rest and a prop.
func _mooch(c: Dictionary, st: Dictionary, keep: int) -> Vector2i:
	var rng: RandomNumberGenerator = c["rng"]
	if rng.randf() > float(st.get("restless", 0.35)):
		return Vector2i.ZERO
	var here: Vector2i = c["cell"]
	var options: Array[Vector2i] = []
	for d in CARDINALS:
		var n: Vector2i = here + d
		if _walkable(n) and not _occupied(n, c) and _chebyshev(n, c["home"]) <= maxi(1, keep):
			options.append(d)
	if options.is_empty():
		return Vector2i.ZERO
	return options[rng.randi_range(0, options.size() - 1)]


func _greedy(here: Vector2i, aim: Vector2i, c: Dictionary) -> Vector2i:
	var delta := aim - here
	var order: Array[Vector2i] = []
	var hx := Vector2i(signi(delta.x), 0)
	var hy := Vector2i(0, signi(delta.y))
	if absi(delta.x) >= absi(delta.y):
		order = [hx, hy]
	else:
		order = [hy, hx]
	for d in order:
		if d == Vector2i.ZERO:
			continue
		if _walkable(here + d) and not _occupied(here + d, c):
			return d
	return Vector2i.ZERO


## Breadth-first distances outward from `from_cell`, stopping as soon as `seek`
## has a number on it or the budget runs out. The budget is what keeps this
## free: it is a bound on cells expanded, not on distance, so an open field and
## a warren cost the same worst case.
func _flood(from_cell: Vector2i, seek: Vector2i) -> Dictionary:
	var dist: Dictionary = {from_cell: 0}
	var queue: Array[Vector2i] = [from_cell]
	var head := 0
	var budget := path_budget()
	while head < queue.size() and head < budget:
		var at: Vector2i = queue[head]
		head += 1
		if at == seek:
			return dist
		var d: int = int(dist[at]) + 1
		for step in CARDINALS:
			var n: Vector2i = at + step
			if dist.has(n) or not _walkable(n):
				continue
			dist[n] = d
			queue.append(n)
	return dist


## Put it back where it should be. Used both by `recover` and by coming back to
## the overworld: the nearest walkable, unoccupied cell at the edge of the band.
func _place_near(c: Dictionary, aim: Vector2i, keep: int) -> void:
	var want := maxi(1, keep)
	var best := Vector2i(-1, -1)
	var best_score := 1 << 30
	for radius in range(want, want + 4):
		for dy in range(-radius, radius + 1):
			for dx in range(-radius, radius + 1):
				if maxi(absi(dx), absi(dy)) != radius:
					continue          # the ring, not the filled square
				var n := aim + Vector2i(dx, dy)
				if not _walkable(n) or _occupied(n, c):
					continue
				var score := absi(radius - want) * 100 + _chebyshev(n, c["cell"])
				if score < best_score:
					best_score = score
					best = n
		if best.x >= 0:
			break
	if best.x < 0:
		return
	c["cell"] = best
	c["from"] = best
	c["t"] = 1.0
	_face_toward(c, aim)
	_dirty = true


func _face_toward(c: Dictionary, aim: Vector2i) -> void:
	var delta: Vector2i = aim - c["cell"]
	if delta == Vector2i.ZERO:
		return
	if absi(delta.x) >= absi(delta.y):
		c["facing"] = Vector2i(signi(delta.x), 0)
	else:
		c["facing"] = Vector2i(0, signi(delta.y))


func _walkable(cell: Vector2i) -> bool:
	return world().walkable(cell.x, cell.y)


## Two animals may not share a cell, and neither may stand on the player. The
## player is excluded from the *flood* rather than from it, deliberately: a
## player standing in a doorway would otherwise make the whole far side of the
## house unreachable and the dog would give up on a route he only had to wait
## one tick for.
func _occupied(cell: Vector2i, self_c: Dictionary) -> bool:
	if cell == _player:
		return true
	for entry in _live:
		var other: Dictionary = entry
		if String(other["key"]) == String(self_c["key"]):
			continue
		if other["cell"] == cell or (float(other["t"]) < 1.0 and other["from"] == cell):
			return true
	return false


static func _chebyshev(a: Vector2i, b: Vector2i) -> int:
	return maxi(absi(a.x - b.x), absi(a.y - b.y))


## How far the player is from one animal, for tests and for anything that wants
## to know without reaching into the live array.
func distance_to_player(key: String) -> int:
	var c := _find(key)
	if c.is_empty() or _player.x < 0:
		return -1
	return _chebyshev(c["cell"], _player)


func _find(key: String) -> Dictionary:
	for entry in _live:
		if String((entry as Dictionary)["key"]) == key:
			return entry
	return {}


# --- persistence ---------------------------------------------------------------
# The dog following you is run state: it was caused by something the player did
# and it must still be true after the phone is killed. Position moves constantly
# so it is not written on every step — every few seconds while dirty, and always
# the moment a state changes or the overworld stops being on screen.

func _flush(delta: float) -> void:
	if not _dirty:
		return
	_save_in -= delta
	if _save_in > 0.0:
		return
	save_state()


func save_state() -> void:
	_dirty = false
	_save_in = SAVE_SECONDS
	var rows: Array = []
	for entry in _live:
		var c: Dictionary = entry
		rows.append({
			"key": String(c["key"]), "id": String(c["id"]), "state": String(c["state"]),
			"x": int(c["cell"].x), "y": int(c["cell"].y),
			"hx": int(c["home"].x), "hy": int(c["home"].y),
			"fx": int(c["facing"].x), "fy": int(c["facing"].y),
			"held": float(c["held"]), "stray": int(c["stray"]),
		})
	var f := FileAccess.open(path, FileAccess.WRITE)
	if f == null:
		return
	f.store_string(JSON.stringify({
		"version": VERSION, "seed": _run_seed_now(), "critters": rows}))
	f.close()


## True if a saved set was restored. A save from a different run is dropped
## rather than resumed — the animals belong to the loop that was running.
func load_state() -> bool:
	_live.clear()
	if not FileAccess.file_exists(path):
		return false
	var parsed: Variant = JSON.parse_string(FileAccess.get_file_as_string(path))
	if not (parsed is Dictionary):
		return false
	var doc: Dictionary = parsed
	if int(doc.get("version", 0)) != VERSION:
		return false
	if int(doc.get("seed", 0)) != _run_seed_now():
		return false
	_run_seed = _run_seed_now()
	_seed_seen = _run_seed
	for entry in doc.get("critters", []):
		if not (entry is Dictionary):
			continue
		var row: Dictionary = entry
		var def := species(String(row.get("id", "")))
		if def.is_empty():
			continue          # a species deleted from the data is not a ghost
		var state := String(row.get("state", ""))
		if not (def.get("states", {}) as Dictionary).has(state):
			state = String(def.get("start", ""))
		var c := _make(String(row.get("key", "")), String(row.get("id", "")), def,
			Vector2i(int(row.get("hx", 0)), int(row.get("hy", 0))),
			Vector2i(int(row.get("x", 0)), int(row.get("y", 0))), state)
		c["facing"] = Vector2i(int(row.get("fx", 0)), int(row.get("fy", 1)))
		c["held"] = float(row.get("held", 0.0))
		c["stray"] = int(row.get("stray", 0))
		_live.append(c)
	_spawned = true
	changed.emit()
	return not _live.is_empty()


func _run_seed_now() -> int:
	if Game != null and Game.run != null:
		return int(Game.run.seed)
	return _run_seed
