class_name HJWorld
extends RefCounted
## The world. One of them, loaded once.
##
## Eight areas used to mean eight generated maps with a wall round each. They
## are now eight *regions* of one continuous landscape: the bed you wake in is a
## room in a house, the house stands at the edge of a town, and the mountain is
## at the top of the same grid. Nothing stops you walking to the summit on day
## one — you will simply find the door shut.
##
## The grid is generated by tools/make_world.py, which writes both this and the
## drawn map in assets/world/worldmap.png from the same source, so the map and
## the ground can never disagree.

## Tile ids index ORDER in tools/make_tiles.py.
const PATH := "res://data/world/overworld.json"
const MANIFEST := "res://assets/tiles/tiles.json"
const T_DOOR := 5

## Which ids cannot be stood on, read from the tileset's own manifest rather
## than copied here.
##
## This was a hardcoded [6, 7, 8, 9, 10, 16]. The tileset then grew from 18
## tiles to 25 and three of the new ones — ocean, jungle, cliff — are solid, so
## the copy was silently wrong the moment the art changed and the player could
## walk into the sea. A second copy of a list is a second chance to disagree
## with it; make_tiles.py publishes the truth and this reads it.
var solid: Dictionary = {}

## Draw order for the overlay stack, from the manifest. A material only bleeds
## onto ones *below* it, so water laps over sand and the road lies over
## everything — the rank is what decides which of two neighbours does the
## intruding, and without it every boundary would be drawn twice.
var rank: Dictionary = {}          ## tile id -> rank, 0 = lowest
var overlay_slot: Dictionary = {}  ## tile id -> row block in overlays.png
var variant_count := 0

## What is standing on each cell, and what that makes impassable. A prop's art
## is 64x96 and its collision is the cell or two under its foot, so the two are
## separate planes rather than one derived from the other.
var props: PackedByteArray = PackedByteArray()
var blocked: PackedByteArray = PackedByteArray()
var prop_solid: Dictionary = {}

## The second prop plane (#83): what lies on the cell, or on the prop standing
## on it — grit in a lane, a rug, a cup on a counter. Its own catalogue with
## its own 1..255, so plane id 5 here and plane id 5 in `props` are two
## different things that may be on the same cell, and the catalogue is no
## longer capped at 255 entries in total.
##
## NOT part of `blocked`, and not by convention: the generator derives the
## collision plane from `props` and `cliffs` alone and never sees this one, so
## there is nothing here for walkable() to consult.
var clutter: PackedByteArray = PackedByteArray()
## Clutter plane id -> true when the art lies flat on the ground rather than
## sitting on top of whatever is standing there. It decides DRAW ORDER within
## one cell and nothing else: flat clutter goes under the prop (grit round the
## foot of a bush), everything else goes over it (the cup on the counter).
## Read from the manifest's own `flat`, which is the same word scatter_props()
## reads to decide what may lie in a lane.
var clutter_under: Dictionary = {}

## Elevation quantised into steps. A smooth field has nowhere to put a cliff;
## terraces give it edges. The generator derives its cliff collision from this
## same plane, so the wall you can see and the wall you cannot walk through are
## the same wall.
## 0 none, 1 left end, 2 middle, 3 right end. Baked by the generator because
## whether a cell is a cliff depends on how far the drop runs either side of it,
## which is not a question the renderer can answer per frame.
var cliffs: PackedByteArray = PackedByteArray()

var w: int = 0
var h: int = 0
var tiles: PackedByteArray = PackedByteArray()
var regions: Dictionary = {}          ## area id -> Vector2i
## The area ids that claim a whole rectangle rather than only an anchor, and the
## rectangle each one claims. A point cannot describe a valley: `the_town` was
## one anchor at (128, 128) and place_id() gave up beyond 24 tiles, so the
## tavern, the mill and the whole west bank answered "Outside" and every
## conversation held in them was drawn against the wrong backdrop plate.
var region_rects: Dictionary = {}     ## area id -> Rect2i
## Rectangles the tutorial treats as "inside". The Boon of the White Room makes
## walking free indoors and breaks the moment the player crosses out, and that
## crossing also unlocks the Hearth and puts Spite on the doorstep — so the
## engine needs a hard answer to "am I still in the house". Deriving it from the
## floor material would break the first time someone lays a plank floor on a
## porch; a rectangle the map editor can drag is honest and adjustable.
var indoors: Array[Rect2i] = []
## What each rect of `indoors` is called, index for index. Empty means "Home".
var _indoor_names: Array[String] = []
var spawn := Vector2i.ZERO
var loaded := false

static var _shared: HJWorld = null


## One instance for the whole app. 48,000 cells is 47KB in memory and there is
## only ever one world, so re-decoding it per screen would be pure waste.
static func shared() -> HJWorld:
	if _shared == null:
		_shared = HJWorld.new()
		_shared.load_world()
	return _shared


func load_world() -> void:
	if not ResourceLoader.exists(PATH) and not FileAccess.file_exists(PATH):
		push_error("HJWorld: %s missing — run tools/make_world.py" % PATH)
		return
	var file := FileAccess.open(PATH, FileAccess.READ)
	if file == null:
		push_error("HJWorld: cannot open %s" % PATH)
		return
	var parsed = JSON.parse_string(file.get_as_text())
	file.close()
	if not (parsed is Dictionary):
		push_error("HJWorld: %s is not valid JSON" % PATH)
		return

	w = int(parsed.get("w", 0))
	h = int(parsed.get("h", 0))
	var packed := Marshalls.base64_to_raw(String(parsed.get("tiles_b64_deflate", "")))
	tiles = packed.decompress(w * h, FileAccess.COMPRESSION_DEFLATE)
	if tiles.size() != w * h:
		push_error("HJWorld: decoded %d cells, expected %d" % [tiles.size(), w * h])
		return

	region_rects.clear()
	for id in parsed.get("regions", {}):
		var cell: Dictionary = parsed["regions"][id]
		regions[String(id)] = Vector2i(int(cell.get("x", 0)), int(cell.get("y", 0)))
		# A region may also say how far it reaches. Optional, because most of
		# them are a spot on a hillside and a spot is the honest answer for
		# those; a town is not a spot.
		var box: Variant = cell.get("rect", null)
		if box is Dictionary:
			region_rects[String(id)] = Rect2i(
				int(box.get("x", 0)), int(box.get("y", 0)),
				int(box.get("w", 0)), int(box.get("h", 0)))
	props = _plane(parsed, "props_b64_deflate")
	clutter = _plane(parsed, "clutter_b64_deflate")
	blocked = _plane(parsed, "blocked_b64_deflate")
	cliffs = _plane(parsed, "cliffs_b64_deflate")
	indoors.clear()
	# Accepts one rect or a list of them, because a floor plan that is not a
	# rectangle is normal and the alternative is the map lying about itself.
	var rooms: Variant = parsed.get("indoors", [])
	_indoor_names.clear()
	for entry in (rooms if rooms is Array else [rooms]):
		if entry is Dictionary:
			indoors.append(Rect2i(int(entry.get("x", 0)), int(entry.get("y", 0)),
				int(entry.get("w", 0)), int(entry.get("h", 0))))
			# A rect may say what building it is. Until the town's buildings
			# carry names, every interior answered "Home", which is why they
			# could not be added to this list at all: the tavern would have
			# introduced itself as the player's house. A rect with no name
			# still means home, so the house needs no entry.
			_indoor_names.append(String(entry.get("place", "")))
	interactables = parsed.get("interactables", [])
	_interactable_at.clear()
	for entry in interactables:
		if entry is Dictionary:
			_interactable_at[Vector2i(int(entry.get("x", 0)), int(entry.get("y", 0)))] = entry
	anomalies = parsed.get("anomalies", [])
	_anomaly_at.clear()
	for a in anomalies:
		var entry: Dictionary = a
		_anomaly_at[Vector2i(int(entry.get("x", 0)), int(entry.get("y", 0)))] = entry
	var s: Dictionary = parsed.get("spawn", {})
	spawn = Vector2i(int(s.get("x", 0)), int(s.get("y", 0)))
	_load_solid()
	loaded = true


## Falls back to nothing-is-solid rather than to a stale guess: a world you can
## walk through is an obvious bug, where a world with the wrong walls is a
## subtle one that looks like level design.
func _load_solid() -> void:
	solid.clear()
	var file := FileAccess.open(MANIFEST, FileAccess.READ)
	if file == null:
		push_error("HJWorld: %s missing — run tools/make_tiles.py" % MANIFEST)
		return
	var parsed = JSON.parse_string(file.get_as_text())
	file.close()
	if not (parsed is Dictionary):
		return
	for id in parsed.get("solid_ids", []):
		solid[int(id)] = true

	# Which clutter ids lie flat. Built here rather than asked of the manifest
	# per cell per frame: the renderer needs the answer inside its row loop and
	# the answer never changes once the art is built.
	clutter_under.clear()
	for row in (parsed.get("clutter", {}) as Dictionary).get("list", []):
		var entry: Dictionary = row
		if bool(entry.get("flat", false)):
			clutter_under[int(entry.get("plane", 0))] = true

	var order: Array = parsed.get("order", [])
	var index: Dictionary = {}
	for i in range(order.size()):
		index[String(order[i])] = i
	var precedence: Array = parsed.get("precedence", [])
	for r in range(precedence.size()):
		var name := String(precedence[r])
		if not index.has(name):
			continue
		rank[int(index[name])] = r
		# Rank 0 owns no edge set — nothing is below it to bleed onto — so the
		# atlas holds ranks 1 and up and the slot is one less than the rank.
		if r > 0:
			overlay_slot[int(index[name])] = r - 1
	variant_count = int(parsed.get("variants", {}).get("count", 0))


## One byte per cell, or empty if the key is absent — an older world file should
## render without props rather than refuse to load.
func _plane(parsed: Dictionary, key: String) -> PackedByteArray:
	var raw := String(parsed.get(key, ""))
	if raw == "":
		return PackedByteArray()
	var out := Marshalls.base64_to_raw(raw).decompress(w * h, FileAccess.COMPRESSION_DEFLATE)
	return out if out.size() == w * h else PackedByteArray()


## The prop standing on a cell, 0 for none. The value is the manifest's `plane`,
## which is the atlas slot plus one.
## Which cliff piece stands on a cell, 0 for none.
func cliff_at(x: int, y: int) -> int:
	var i := y * w + x
	if x < 0 or y < 0 or x >= w or y >= h or i >= cliffs.size():
		return 0
	return cliffs[i]


func prop_at(x: int, y: int) -> int:
	var i := y * w + x
	if x < 0 or y < 0 or x >= w or y >= h or i >= props.size():
		return 0
	return props[i]


## What lies on a cell, or on the prop standing on it. 0 for none, and the
## value indexes the manifest's `clutter` list, not its `props` list.
func clutter_at(x: int, y: int) -> int:
	var i := y * w + x
	if x < 0 or y < 0 or x >= w or y >= h or i >= clutter.size():
		return 0
	return clutter[i]


func at(x: int, y: int) -> int:
	# The size check is not paranoia: a world that failed to load leaves an empty
	# array, and without this every draw call becomes a thousand out-of-bounds
	# errors that bury the one message saying why.
	var i := y * w + x
	if x < 0 or y < 0 or x >= w or y >= h or i >= tiles.size():
		return 10          # void
	return tiles[i]


func walkable(x: int, y: int) -> bool:
	var i := y * w + x
	if i >= 0 and i < blocked.size() and blocked[i] != 0:
		return false
	if not solid.has(at(x, y)):
		return not _shut(Vector2i(x, y))
	return false


## What to call where you are standing.
##
## The overworld header used to read `run.area.get("name", "Area")`, and outside
## an anomaly there is no area — so a player walking around their own house was
## told they were in "Area". The world knows better than the run does: it has
## named regions and it knows what is indoors.
func place_name(cell: Vector2i) -> String:
	var inside := indoor_index(cell)
	if inside >= 0:
		var named := _indoor_names[inside] if inside < _indoor_names.size() else ""
		return named if named != "" else "Home"
	var best := place_id(cell)
	if best == "":
		return "Outside"
	# `place`, not `name`. A region id doubles as an area id, and an area's name
	# belongs to the *memory* you walk into — `waking_room` is called "The
	# Asking" — so borrowing it told a player standing on their own doorstep
	# that they were in the anomaly they had not entered. `place` is what the
	# spot is called when you are merely near it.
	var area := Content.area(best)
	return String(area.get("place", area.get("name", best)))


## Which named region this cell belongs to, or "". A region id doubles as an
## area id, which is what lets a caller reach for that area's backdrop: a
## conversation in the town square was drawn against the bedroom because the
## only question anyone asked was which *anomaly* the run was in, and standing
## in the town you are in none.
func place_id(cell: Vector2i) -> String:
	# A CONTAINING RECTANGLE BEATS THE NEAREST ANCHOR, and the smallest
	# containing rectangle beats a bigger one. Nearest-anchor alone cannot say
	# "this whole valley is the town" without also claiming the mountain, and
	# widening its radius until the town fits swallows the house that stands at
	# the edge of it. Rects nest instead: the vale is the town, the plot around
	# the house is inside the vale, and the smaller claim wins where they
	# overlap, which is why a player on their own doorstep is still at home.
	var claimed := ""
	var claimed_area := 1 << 30
	for id in region_rects:
		var box: Rect2i = region_rects[id]
		if not box.has_point(cell):
			continue
		var area: int = box.size.x * box.size.y
		if area < claimed_area:
			claimed_area = area
			claimed = String(id)
	if claimed != "":
		return claimed

	var best := ""
	var best_d := 1 << 30
	for id in regions:
		var at: Vector2i = regions[id]
		var d: int = absi(at.x - cell.x) + absi(at.y - cell.y)
		if d < best_d:
			best_d = d
			best = String(id)
	# Far from everything named is its own answer. Claiming you are in the
	# Observatory because it is the closest anchor forty tiles away is worse
	# than admitting the map has nothing to say about here.
	return "" if best_d > 24 else best


## Which building this cell is inside, or -1. Separate from `is_indoors` so a
## caller that only wants the yes-or-no is not made to care about the index.
func indoor_index(cell: Vector2i) -> int:
	for i in indoors.size():
		if indoors[i].has_point(cell):
			return i
	return -1


## Is this cell inside a building?
func is_indoors(cell: Vector2i) -> bool:
	for r in indoors:
		if r.has_point(cell):
			return true
	return false


## Every interactable placed in the world, and the one on a given cell.
var interactables: Array = []
var _interactable_at: Dictionary = {}


func interactable_at(cell: Vector2i) -> Dictionary:
	return _interactable_at.get(cell, {})


## A door standing in the way because it has not been paid for yet.
##
## This is what gates the house: the exit is a Grit purchase, not a reward for
## finishing an anomaly. Leaving is a thing you buy, which is the whole lesson
## of Beat 4 — and expressing it as an unwalkable cell rather than a special
## case in the movement code means every path query already respects it.
func _shut(cell: Vector2i) -> bool:
	var entry: Dictionary = _interactable_at.get(cell, {})
	if entry.is_empty():
		return false
	var kind := Content.interactable(String(entry.get("type", "")))
	# A run tag for anything the loop takes back — the front door is bought
	# again every morning — and an objective for anything it does not. The fort
	# gate is the second kind: the children have to be convinced once, and a
	# player who has already walked out past them should not have to argue it
	# again every loop. Gating that on a run tag would also have made the Hearth
	# report a permanently finished errand while the children stood in the road
	# refusing to move, which is the interface lying about the world.
	var done := String(kind.get("blocks_until_objective", ""))
	if done != "" and not Objectives.is_complete(done):
		return true
	var gate := String(kind.get("blocks_until_tag", ""))
	return gate != "" and not Game.has_tag(gate)


## Every anomaly in the world, and the one on a given cell.
var anomalies: Array = []
var _anomaly_at: Dictionary = {}


func anomaly_at(cell: Vector2i) -> Dictionary:
	return _anomaly_at.get(cell, {})


## The tier of the anomaly on a cell, or -1 for none. Separate from anomaly_at
## because the renderer asks this per cell per frame and does not want a
## dictionary lookup's worth of allocation to find out the answer is usually no.
func anomaly_tier(x: int, y: int) -> int:
	var entry: Dictionary = _anomaly_at.get(Vector2i(x, y), {})
	return int(entry.get("tier", -1)) if not entry.is_empty() else -1


func anchor(area_id: String) -> Vector2i:
	return regions.get(area_id, spawn)


## Somewhere to stand near a target. Spirals outward rather than giving up,
## because a story beat that lands in a wall is a run the player cannot finish.
func nearest_walkable(from: Vector2i, limit: int = 40) -> Vector2i:
	if walkable(from.x, from.y):
		return from
	for r in range(1, limit):
		for dy in range(-r, r + 1):
			for dx in range(-r, r + 1):
				if absi(dx) != r and absi(dy) != r:
					continue        # ring only, not the filled square
				var cell := from + Vector2i(dx, dy)
				if walkable(cell.x, cell.y):
					return cell
	return from


## Where this anomaly's nodes stand in the world.
##
## Placed on a ring around the region's anchor rather than in graph rows: the
## world already has a shape, and imposing a tidy lattice on it would put nodes
## in the sea. Deterministic from the run seed and the node id, so a node keeps
## its spot for as long as the run lasts.
func place_nodes(run: HJRun) -> Dictionary:
	var out: Dictionary = {}
	# The anomaly you stepped into is the centre. Its nodes belong to the place
	# you are standing, not to a region anchor picked from a sequence.
	var centre := Vector2i(int(run.anomaly.get("x", -1)), int(run.anomaly.get("y", -1)))
	if centre.x < 0:
		centre = anchor(String(run.area.get("id", "")))
	var ids: Array = run.area.get("order", [])
	if ids.is_empty():
		return out
	var taken: Array[Vector2i] = []
	for i in range(ids.size()):
		var id := String(ids[i])
		# Golden-angle spiral: even coverage without clumping, and adding a node
		# never moves the ones already placed.
		var t := float(i)
		var angle := t * 2.39996
		var radius := 3.0 + sqrt(t) * 4.6
		var want := centre + Vector2i(
			int(round(cos(angle) * radius)), int(round(sin(angle) * radius * 0.85)))
		var cell := nearest_walkable(want)
		var guard := 0
		while taken.has(cell) and guard < 24:
			guard += 1
			cell = nearest_walkable(cell + Vector2i(1, 0))
		taken.append(cell)
		out[cell] = id
	return out
