class_name HJWorld
extends RefCounted
## The world. One of them, loaded once.
##
## Eight chapters used to mean eight generated maps with a wall round each. They
## are now eight *regions* of one continuous landscape: the bed you wake in is a
## room in a house, the house stands at the edge of a town, and the mountain is
## at the top of the same grid. Nothing stops you walking to the summit on day
## one — you will simply find the door shut.
##
## The grid is generated by tools/make_world.py, which writes both this and the
## drawn map in assets/world/worldmap.png from the same source, so the map and
## the ground can never disagree.

## Tile ids index ORDER in tools/make_tiles.py.
const PATH := "res://data/world/overworld.json"
const MANIFEST := "res://assets/tiles/tiles.json"
const T_DOOR := 5

## Which ids cannot be stood on, read from the tileset's own manifest rather
## than copied here.
##
## This was a hardcoded [6, 7, 8, 9, 10, 16]. The tileset then grew from 18
## tiles to 25 and three of the new ones — ocean, jungle, cliff — are solid, so
## the copy was silently wrong the moment the art changed and the player could
## walk into the sea. A second copy of a list is a second chance to disagree
## with it; make_tiles.py publishes the truth and this reads it.
var solid: Dictionary = {}

## Draw order for the overlay stack, from the manifest. A material only bleeds
## onto ones *below* it, so water laps over sand and the road lies over
## everything — the rank is what decides which of two neighbours does the
## intruding, and without it every boundary would be drawn twice.
var rank: Dictionary = {}          ## tile id -> rank, 0 = lowest
var overlay_slot: Dictionary = {}  ## tile id -> row block in overlays.png
var variant_count := 0

## What is standing on each cell, and what that makes impassable. A prop's art
## is 64x96 and its collision is the cell or two under its foot, so the two are
## separate planes rather than one derived from the other.
var props: PackedByteArray = PackedByteArray()
var blocked: PackedByteArray = PackedByteArray()
var prop_solid: Dictionary = {}

## Elevation quantised into steps. A smooth field has nowhere to put a cliff;
## terraces give it edges. The generator derives its cliff collision from this
## same plane, so the wall you can see and the wall you cannot walk through are
## the same wall.
## 0 none, 1 left end, 2 middle, 3 right end. Baked by the generator because
## whether a cell is a cliff depends on how far the drop runs either side of it,
## which is not a question the renderer can answer per frame.
var cliffs: PackedByteArray = PackedByteArray()

var w: int = 0
var h: int = 0
var tiles: PackedByteArray = PackedByteArray()
var regions: Dictionary = {}          ## area id -> Vector2i
var spawn := Vector2i.ZERO
var loaded := false

static var _shared: HJWorld = null


## One instance for the whole app. 48,000 cells is 47KB in memory and there is
## only ever one world, so re-decoding it per screen would be pure waste.
static func shared() -> HJWorld:
	if _shared == null:
		_shared = HJWorld.new()
		_shared.load_world()
	return _shared


func load_world() -> void:
	if not ResourceLoader.exists(PATH) and not FileAccess.file_exists(PATH):
		push_error("HJWorld: %s missing — run tools/make_world.py" % PATH)
		return
	var file := FileAccess.open(PATH, FileAccess.READ)
	if file == null:
		push_error("HJWorld: cannot open %s" % PATH)
		return
	var parsed = JSON.parse_string(file.get_as_text())
	file.close()
	if not (parsed is Dictionary):
		push_error("HJWorld: %s is not valid JSON" % PATH)
		return

	w = int(parsed.get("w", 0))
	h = int(parsed.get("h", 0))
	var packed := Marshalls.base64_to_raw(String(parsed.get("tiles_b64_deflate", "")))
	tiles = packed.decompress(w * h, FileAccess.COMPRESSION_DEFLATE)
	if tiles.size() != w * h:
		push_error("HJWorld: decoded %d cells, expected %d" % [tiles.size(), w * h])
		return

	for id in parsed.get("regions", {}):
		var cell: Dictionary = parsed["regions"][id]
		regions[String(id)] = Vector2i(int(cell.get("x", 0)), int(cell.get("y", 0)))
	props = _plane(parsed, "props_b64_deflate")
	blocked = _plane(parsed, "blocked_b64_deflate")
	cliffs = _plane(parsed, "cliffs_b64_deflate")
	var s: Dictionary = parsed.get("spawn", {})
	spawn = Vector2i(int(s.get("x", 0)), int(s.get("y", 0)))
	_load_solid()
	loaded = true


## Falls back to nothing-is-solid rather than to a stale guess: a world you can
## walk through is an obvious bug, where a world with the wrong walls is a
## subtle one that looks like level design.
func _load_solid() -> void:
	solid.clear()
	var file := FileAccess.open(MANIFEST, FileAccess.READ)
	if file == null:
		push_error("HJWorld: %s missing — run tools/make_tiles.py" % MANIFEST)
		return
	var parsed = JSON.parse_string(file.get_as_text())
	file.close()
	if not (parsed is Dictionary):
		return
	for id in parsed.get("solid_ids", []):
		solid[int(id)] = true

	var order: Array = parsed.get("order", [])
	var index: Dictionary = {}
	for i in range(order.size()):
		index[String(order[i])] = i
	var precedence: Array = parsed.get("precedence", [])
	for r in range(precedence.size()):
		var name := String(precedence[r])
		if not index.has(name):
			continue
		rank[int(index[name])] = r
		# Rank 0 owns no edge set — nothing is below it to bleed onto — so the
		# atlas holds ranks 1 and up and the slot is one less than the rank.
		if r > 0:
			overlay_slot[int(index[name])] = r - 1
	variant_count = int(parsed.get("variants", {}).get("count", 0))


## One byte per cell, or empty if the key is absent — an older world file should
## render without props rather than refuse to load.
func _plane(parsed: Dictionary, key: String) -> PackedByteArray:
	var raw := String(parsed.get(key, ""))
	if raw == "":
		return PackedByteArray()
	var out := Marshalls.base64_to_raw(raw).decompress(w * h, FileAccess.COMPRESSION_DEFLATE)
	return out if out.size() == w * h else PackedByteArray()


## The prop standing on a cell, 0 for none. The value is the manifest's `plane`,
## which is the atlas slot plus one.
## Which cliff piece stands on a cell, 0 for none.
func cliff_at(x: int, y: int) -> int:
	var i := y * w + x
	if x < 0 or y < 0 or x >= w or y >= h or i >= cliffs.size():
		return 0
	return cliffs[i]


func prop_at(x: int, y: int) -> int:
	var i := y * w + x
	if x < 0 or y < 0 or x >= w or y >= h or i >= props.size():
		return 0
	return props[i]


func at(x: int, y: int) -> int:
	# The size check is not paranoia: a world that failed to load leaves an empty
	# array, and without this every draw call becomes a thousand out-of-bounds
	# errors that bury the one message saying why.
	var i := y * w + x
	if x < 0 or y < 0 or x >= w or y >= h or i >= tiles.size():
		return 10          # void
	return tiles[i]


func walkable(x: int, y: int) -> bool:
	var i := y * w + x
	if i >= 0 and i < blocked.size() and blocked[i] != 0:
		return false
	return not solid.has(at(x, y))


func anchor(area_id: String) -> Vector2i:
	return regions.get(area_id, spawn)


## Somewhere to stand near a target. Spirals outward rather than giving up,
## because a story beat that lands in a wall is a run the player cannot finish.
func nearest_walkable(from: Vector2i, limit: int = 40) -> Vector2i:
	if walkable(from.x, from.y):
		return from
	for r in range(1, limit):
		for dy in range(-r, r + 1):
			for dx in range(-r, r + 1):
				if absi(dx) != r and absi(dy) != r:
					continue        # ring only, not the filled square
				var cell := from + Vector2i(dx, dy)
				if walkable(cell.x, cell.y):
					return cell
	return from


## Where this chapter's nodes stand in the world.
##
## Placed on a ring around the region's anchor rather than in graph rows: the
## world already has a shape, and imposing a tidy lattice on it would put nodes
## in the sea. Deterministic from the run seed and the node id, so a node keeps
## its spot for as long as the run lasts.
func place_nodes(run: HJRun) -> Dictionary:
	var out: Dictionary = {}
	var centre := anchor(String(run.chapter_def().get("area", "waking_room")))
	var ids: Array = run.area.get("order", [])
	if ids.is_empty():
		return out
	var taken: Array[Vector2i] = []
	for i in range(ids.size()):
		var id := String(ids[i])
		# Golden-angle spiral: even coverage without clumping, and adding a node
		# never moves the ones already placed.
		var t := float(i)
		var angle := t * 2.39996
		var radius := 3.0 + sqrt(t) * 4.6
		var want := centre + Vector2i(
			int(round(cos(angle) * radius)), int(round(sin(angle) * radius * 0.85)))
		var cell := nearest_walkable(want)
		var guard := 0
		while taken.has(cell) and guard < 24:
			guard += 1
			cell = nearest_walkable(cell + Vector2i(1, 0))
		taken.append(cell)
		out[cell] = id
	return out
