/* Registers the service worker.
 *
 * Kept out of index.html because that file is generated by the Godot export and
 * everything we add there has to survive being escaped into export_presets.cfg.
 *
 * Service workers need a secure context, so this is a no-op on the plain-HTTP
 * LAN address (http://192.168.x.x:8070) and works on localhost and on the HTTPS
 * hostname. That is a browser rule, not a bug — install the app from the HTTPS
 * URL.
 */
(function () {
  "use strict";
  if (!("serviceWorker" in navigator)) return;

  window.addEventListener("load", function () {
    navigator.serviceWorker.register("sw.js", { scope: "./" }).then(
      function (reg) {
        // A new worker takes over immediately (skipWaiting + clients.claim), so
        // there is nothing to prompt about — the next load is already current.
        reg.addEventListener("updatefound", function () {
          console.log("[pwa] update downloading");
        });
      },
      function (err) {
        console.log("[pwa] service worker not registered:", err.message);
      }
    );
  });
})();
